/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "rcc.h"
#include "gpio.h"

void delay(void)
{
	for(volatile uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
	RCC_AHB1_Init(GpioD, ENABLE);

	GPIO_Handle_t ledGreen;
	ledGreen.GPIOx = GPIOD;
	ledGreen.pinConfig.GPIO_pinNum = GPIOPin12;
	ledGreen.pinConfig.GPIO_mode = GPIO_output;
	ledGreen.pinConfig.GPIO_ospeed = GPIO_high;
	ledGreen.pinConfig.GPIO_otype = GPIO_pushPull;
	ledGreen.pinConfig.GPIO_pupdtype = GPIO_noPupd;

	GPIO_Init(&ledGreen);

	while(1)
	{
		GPIO_Toggle(&ledGreen);
		delay();
	}
}
