/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "bootloader.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	//bootloader_JumpToApplication();
	uint32_t addr = (uint32_t)0x08020000;
	uint32_t len = 256;
	uint32_t data[64];
	uint32_t buffer[70];
	for(uint8_t i = 0; i < len/4; i++)
	{
		data[i] = 0x12345678;
	}
	flash_Unlock();
	flash_SetPrgSize();
	flash_SectorErase(SECTOR5);
	flash_Write(addr, data, sizeof(data));
	flash_Lock();
	flash_Read(addr, buffer, sizeof(data));
    /* Loop forever */
	while(1)
	{

	}
}
