/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

/*
 * This is the second application code that runs when the PA0 button is pressed.
 * It is a very basic baremetal code for sequenced LED blinking : delay() and GPIO_Toggle()
 * The .bin file of this code is sent over TeraTerm using Xmodem protocol over USART to the MCU.
 * The MCU bootloader writes it to the application section of the Flash memory
 * Upon reset+PA0 button press, this application runs
 * */
#include <stdint.h>
#include "stm32f4xx.h"
#include "rcc.h"
#include "gpio.h"

void delay(void)
{
	for(uint32_t i = 0; i < 500000; i++);
}

int main(void)
{
    GPIO_Handle_t greenLed, redLed, orangeLed, blueLed;

    RCC_AHB1_Init(GpioD, ENABLE);

    greenLed.GPIOx = GPIOD;
    greenLed.pinConfig.GPIO_mode = GPIO_output;
    greenLed.pinConfig.GPIO_otype = GPIO_pushPull;
    greenLed.pinConfig.GPIO_ospeed = GPIO_high;
    greenLed.pinConfig.GPIO_pupdtype = GPIO_noPupd;
    greenLed.pinConfig.GPIO_pinNum = GPIOPin12;

    redLed.GPIOx = GPIOD;
	redLed.pinConfig.GPIO_mode = GPIO_output;
	redLed.pinConfig.GPIO_otype = GPIO_pushPull;
	redLed.pinConfig.GPIO_ospeed = GPIO_high;
	redLed.pinConfig.GPIO_pupdtype = GPIO_noPupd;
	redLed.pinConfig.GPIO_pinNum = GPIOPin14;


	orangeLed.GPIOx = GPIOD;
	orangeLed.pinConfig.GPIO_mode = GPIO_output;
	orangeLed.pinConfig.GPIO_otype = GPIO_pushPull;
	orangeLed.pinConfig.GPIO_ospeed = GPIO_high;
	orangeLed.pinConfig.GPIO_pupdtype = GPIO_noPupd;
	orangeLed.pinConfig.GPIO_pinNum = GPIOPin13;

	blueLed.GPIOx = GPIOD;
	blueLed.pinConfig.GPIO_mode = GPIO_output;
	blueLed.pinConfig.GPIO_otype = GPIO_pushPull;
	blueLed.pinConfig.GPIO_ospeed = GPIO_high;
	blueLed.pinConfig.GPIO_pupdtype = GPIO_noPupd;
	blueLed.pinConfig.GPIO_pinNum = GPIOPin15;

	GPIO_Init(&greenLed);
	GPIO_Init(&orangeLed);
	GPIO_Init(&redLed);
	GPIO_Init(&blueLed);

	GPIO_Led_ON(&greenLed);
	GPIO_Led_ON(&orangeLed);
	GPIO_Led_ON(&redLed);
	GPIO_Led_ON(&blueLed);

	delay();

	while(1)
	{
		GPIO_Toggle(&greenLed);
		delay();
		GPIO_Toggle(&orangeLed);
		delay();
		GPIO_Toggle(&redLed);
		delay();
		GPIO_Toggle(&blueLed);
		delay();
	}
}
